absl-py==0.6.1
adal==1.2.1
addict==2.2.0
alabaster==0.7.12
asgiref==2.3.2
asn1crypto==0.24.0
astor==0.7.1
async-timeout==2.0.1
attrs==19.1.0
audioread==2.1.6
autobahn==19.2.1
Automat==0.7.0
Babel==2.6.0
cachetools==3.1.0
certifi==2019.3.9
cffi==1.11.5
channels==2.1.7
chardet==3.0.4
Click==7.0
clipper-admin==0.3.0
cloudpickle==0.5.3
CommonMark==0.5.4
constantly==15.1.0
cryptography==2.6.1
cycler==0.10.0
Cython==0.29
daphne==2.2.5
dask==0.20.1
decorator==4.3.0
Django==2.0
django-cors-headers==2.4.0
django-crispy-forms==1.7.2
djangorestframework==3.8.2
docker==3.7.0
docker-pycreds==0.4.0
docutils==0.14
easydict==1.8
gast==0.2.0
google-auth==1.6.3
googleapis-common-protos==1.5.3
grpcio==1.15.0
grpcio-tools==1.15.0
hyperlink==18.0.0
idna==2.7
imageio==2.4.1
imagesize==1.1.0
incremental==17.5.0
Jinja2==2.10
joblib==0.13.0
jsonschema==3.0.1
kiwisolver==1.0.1
kubernetes==8.0.1
librosa==0.6.2
llvmlite==0.25.0
Markdown==3.0.1
MarkupSafe==1.1.0
matplotlib==2.2.2
mmcv==0.2.0
msgpack==0.5.6
networkx==2.2
ninja==1.8.2
numba==0.40.1
numpy==1.16.1
oauthlib==3.0.1
opencv-python==3.4.3.18
packaging==18.0
pandas==0.23.4
Pillow==5.4.1
prometheus==0.3.0
prometheus-client==0.5.0
protobuf==3.7.0
psutil==5.6.0
purepng==0.2.0
pyasn1==0.4.5
pyasn1-modules==0.2.4
pybind11==2.2.4
pycocotools==2.0.0
pycparser==2.19
pydub==0.23.0
Pygments==2.2.0
PyHamcrest==1.9.0
PyJWT==1.7.1
pyparsing==2.3.0
pyrsistent==0.14.11
python-dateutil==2.7.5
pytz==2018.7
PyWavelets==1.0.1
PyYAML==3.13
pyzmq==17.0.0
quantile-python==1.1
recommonmark==0.4.0
redis==3.2.0
requests==2.20.1
requests-oauthlib==1.2.0
resampy==0.2.1
rinoh-typeface-dejavuserif==0.1.1
rinoh-typeface-texgyrecursor==0.1.1
rinoh-typeface-texgyreheros==0.1.1
rinoh-typeface-texgyrepagella==0.1.1
rinohtype==0.3.1
rsa==4.0
scenedetect==0.5
scikit-image==0.14.2
scikit-learn==0.20.0
scipy==1.1.0
seaborn==0.9.0
six==1.12.0
snowballstemmer==1.2.1
SoundFile==0.10.2
Sphinx==1.8.1
sphinxcontrib-websupport==1.1.0
tabulate==0.8.2
tensorboard==1.9.0
tensorboardX==1.4
tensorflow-gpu==1.9.0
tensorflow-hub==0.1.1
termcolor==1.1.0
terminaltables==3.1.0
toolz==0.9.0
torch==0.4.1
torchvision==0.2.1
tqdm==4.28.1
Twisted==18.9.0
txaio==18.8.1
urllib3==1.24.1
websocket-client==0.55.0
Werkzeug==0.14.1
zope.interface==4.6.0
torchstat==git+git://github.com/ZhouShengsheng/torchstat.git@master
gputil==git+git://github.com/ZhouShengsheng/gputil.git@master
